name: Build

on:
  push:
  pull_request:

jobs:
  build:
    container: devkitpro/devkitppc:latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - GAME: OOT
          - GAME: MM
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository (shallow clone)
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    # Set Git config
    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    # Build the project
    - name: Build
      run: make GAME=${{ matrix.GAME }}
